// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `decoder_cle`, `decoder_souple`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `fmt`, `from`

/// Scelle un contenu sous une clé neuve, tirée pour ce seul paste.
///
/// L'invariant qui rend sûr le nonce de 96 bits d'AES-GCM est **une clé par paste**, et il
/// appartient à `ghost_crypto::partage` : le tirage reste en Rust, aucun client ne produit
/// de matière cryptographique.
Future<Enveloppe> sceller({required List<int> clair}) =>
    RustLib.instance.api.crateApiCoeurSceller(clair: clair);

/// Ouvre ce que le serveur a rendu. Rend des **octets** et non une chaîne : un paste peut
/// avoir été gzippé avant chiffrement (`compressed: true`), auquel cas ce qui sort n'est
/// pas encore du texte. Forcer l'UTF-8 ici rendrait ces pastes-là impossibles à lire.
Future<Uint8List> ouvrir({
  required String cle,
  required String nonce,
  required String chiffre,
}) => RustLib.instance.api.crateApiCoeurOuvrir(
  cle: cle,
  nonce: nonce,
  chiffre: chiffre,
);

/// Compose le fragment d'une URL de paste : `CLE~JETON`, ou `~JETON` sans clé.
///
/// La forme sans clé n'est pas un cas dégradé, c'est celle des pastes protégés par mot de
/// passe : la clé se dérive chez le lecteur et n'a rien à faire dans le lien.
Future<String> composerFragment({required String cle, required String jeton}) =>
    RustLib.instance.api.crateApiCoeurComposerFragment(cle: cle, jeton: jeton);

/// Analyse le fragment d'une URL reçue.
///
/// Trois formes existent dans la nature et il faut les rendre toutes les trois, sans quoi
/// on refuse des liens parfaitement valides :
///
/// - `CLE~JETON` — ce que voit le créateur, juste après création ;
/// - `~JETON` — un paste protégé par mot de passe, vu par son créateur ;
/// - `CLE` — un lien partagé, dont on a retiré le jeton avant de l'envoyer.
///
/// Le séparateur est cherché à la **première** occurrence : un jeton
/// (`secrets.token_urlsafe`) ne contient jamais de `~`, mais couper à la dernière ferait
/// dépendre le résultat d'une hypothèse qu'on ne contrôle pas.
Future<Fragment> analyserFragment({required String fragment}) =>
    RustLib.instance.api.crateApiCoeurAnalyserFragment(fragment: fragment);

/// Une enveloppe prête à partir : deux champs pour le serveur, un pour le fragment.
///
/// La séparation est celle de l'API de ghostbit, et elle porte tout le modèle : le serveur
/// reçoit `chiffre` et `nonce`, jamais `cle`. Nommer les trois champs dans un même objet
/// est le seul endroit où ils se touchent, et c'est un objet qu'on lit d'un coup d'œil.
class Enveloppe {
  /// Base64 **standard** — c'est le champ `content` de `POST /api/v1/pastes`.
  final String chiffre;

  /// Base64 **standard**, 12 octets une fois décodé — le champ `nonce`.
  final String nonce;

  /// Base64**url** sans remplissage — la part gauche du fragment. Ne part jamais au
  /// serveur : la mettre dans le corps d'une requête serait la fin du modèle.
  final String cle;

  const Enveloppe({
    required this.chiffre,
    required this.nonce,
    required this.cle,
  });

  @override
  int get hashCode => chiffre.hashCode ^ nonce.hashCode ^ cle.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Enveloppe &&
          runtimeType == other.runtimeType &&
          chiffre == other.chiffre &&
          nonce == other.nonce &&
          cle == other.cle;
}

/// L'erreur telle que Dart la verra.
///
/// Le type d'erreur du cœur ne traverse pas : il porte des variantes qui n'ont de sens
/// qu'en Rust. On rend un message, comme le fait déjà le binding UniFFI — ce qui compte,
/// c'est que l'échec soit un échec, pas qu'il soit typé de l'autre côté.
class ErreurDuCoeur implements FrbException {
  final String message;

  const ErreurDuCoeur({required this.message});

  @override
  int get hashCode => message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ErreurDuCoeur &&
          runtimeType == other.runtimeType &&
          message == other.message;
}

/// Ce qu'on retrouve dans un fragment lu depuis une URL reçue.
class Fragment {
  /// Vide pour un paste protégé par mot de passe : la clé s'y dérive, elle ne voyage pas.
  final String cle;

  /// Vide pour qui n'est pas le créateur — un lien partagé se coupe avant le `~`.
  final String jeton;

  const Fragment({required this.cle, required this.jeton});

  @override
  int get hashCode => cle.hashCode ^ jeton.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Fragment &&
          runtimeType == other.runtimeType &&
          cle == other.cle &&
          jeton == other.jeton;
}
